[package]
name = "prime-numbers-counter"
version = "0.1.0"
authors = ["NrdyBhu1@gmail.com <NrdyBhu1>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
